type User {
  id: ID!
  email: String!
  fullName: String!
  password: String!
}

input RegisterInput {
  fullName: String!
  email: String!
  password: String!
  confirmPassword: String!
}

input LoginInput {
  email: String!
  password: String!
}

extend type Mutation {
  registerUser(registerInput: RegisterInput): User!
  loginUser(loginInput: LoginInput): User!
}
